environment:
  semantic_version: 4.0.0

version: $(semantic_version).{build}

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(semantic_version).0'
  assembly_file_version: '$(appveyor_build_version)'
  assembly_informational_version: '$(semantic_version)-CI-{build}'

configuration: Release

before_build:
- nuget restore
- type src\Autofac.Integration.Wcf\Properties\AssemblyInfo.cs

build:
  verbosity: minimal
  publish_nuget: false
  publish_nuget_symbols: false

deploy:
- provider: NuGet
  server: https://www.myget.org/F/autofac/
  api_key:
    secure: N4KZCRegcmenMoJ0peZfQwDzqq+Wt4oxGzNTgvkrDxgWyZhw7hNwKmd4n2AsNKQX
  symbol_server: https://nuget.symbolsource.org/MyGet/autofac